version: '{build}'
image: Visual Studio 2017
configuration: Release

before_build:
- cmd: dotnet restore

artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: c7NLUxWB1cTRpg+1MYfvbjYFzCzm/yz6/53k3EMFoMrCJResdvcZ294t8JpBoFCx
  on:
    appveyor_repo_tag: true
