version: 1.0.{build}

environment:
    CLI_VERSION: Latest

image: Visual Studio 2017

configuration: Release

before_build:
- cmd: dotnet restore

build:
  verbosity: minimal
 
test_script:
  - cmd: dotnet test